#+title: Rapport hebdomadaire
#+subtitle: Contrat Été 2024
#+author: Charles-Édouard Lizotte
#+date:20/09/2024
#+LANGUAGE: fr
#+BIBLIOGRAPHY: master-bibliography.bib
#+OPTIONS: toc:nil title:nil 
#+LaTeX_class: org-report

\mytitlepage
\tableofcontents\newpage

* DONE Objectifs principaux des prochaines semaines 

** Développer une « config » préliminaire de Wavewatch [1/1]

+ [X] Il faut premièrement installer Wavewatch III sur mes machines (On teste sur la mienne en premier, comme ça je pourrai exporter mon environnement sur les machines du PolR ou de /Compute Canada/;
+ [5/5] Faut vérifier que Wavewatch III fonctionne bien.
  - [X] /grid input/ main genre une ligne. Si je me souviens bien, j'ai déjà une fonction Python qui réalise ce genre de fichiers d'entrée (Voir les codes de la maîtrise);
  - [X] /Startfile/, il faut s'assurer que ça marche;
  - [1/1] /NetCDF input/ genre un courant et un vent. On peut clairement prendre la fonction que j'ai développée (/build current.py/);
    - [X] Il a fallu remanier la fonction pour un domaine plus petit, le frontières ne marchainet pas vraiment.
  - [X] Problème de NetCDF avec Fortran? Le problème semble venir de /nc-config/. Finalement, ça venait de l'environnement /NetCDF/ que j'utilisais. IL faut impérativement activer l'environnement /wavenv/ pour faire fonctionner le module Fortran /NetCDF/;
  - [X] Les /inputs/ du shell, faut que ça rentre bel et bien dans la /run/;
  - [X] La /run/ du modèle;
    - Problème avec les /inputs/ ou les /switches/? Il semble que /WW3/ ne produise pas de vagues.

** Mettre le terme non-linéaire dans le code Julia  [3/4]

+ [X] Je doit impérativement contacter Sébastien Dugas;
+ [X] Voir la preuve fournie dans le livre [cite:@kinsman1965their];
+ [X] Répondre à Sébastien Dugas;
+ [ ] Trouver un équivalent en 1 dimension;


** Caractérisation des distributions de floes

+ [ ] Il faut créer une fonction en Python qui crée des distributions de glaces avec les paramètres nécessaires;
  - Concentration de glace $C_g$,
  - Taille des /patches/,
  - Orientation de la distribution



* Config de Wavewatch III

** Installation de Wavewatch

J'ai déjà écrit tout ça dans un rapport avec Louis-Philippe, mais je trouve que c'est important de faire une petite mise à jour avant de se remettre dedans. De plus, ça pourrait être utile à tous les nouveaux employés qui me poseront une question là-dessus.

Avant tout, il faut aller sur [[https://polar.ncep.noaa.gov/waves/wavewatch/distribution/]], c'est là qu'on peut télécharger le modèle sous forme de fichier /.tar/ avec les informations
#+begin_src bash
 >>> username: converter1091
 >>> password: contractor8409
#+end_src
On s'assure d'avoir la version la plus à jour, dans mon cas, c'est la 5.16. Une fois que c'est téléchargé, on peut ouvrir le fichier compressé dans un dossier au choix,
#+begin_src bash
 >>> tar -xvf wwatch3.v5.16.tar.gz -C wavewatch3
#+end_src
On va dans le dossier, on rend l'installateur executable avec
#+begin_src bash
 >>> chmod +x install_ww3_tar 
#+end_src
On peut essayer, mais si nous n'avons pas de compilateur Fortran ou C, ça ne sert pas à grand chose. Pour Arch Linux, on peut tout simplement installer /Gfortran/ à l'aide de la commande
#+begin_src bash
 >>> sudo pacman -Syyu gcc-fortran
#+end_src
Mentionnons qu'on a besoin de NetCDF aussi, alors -- si l'on ne l'a pas déjà -- on peut l'installer à l'aide de
#+begin_src bash
 >>> sudo pacman -S netcdf-fortran 
#+end_src
et on peut vérifier l'installation à l'aide de
#+begin_src bash
 >>> nc-config --version
 OUT /usr/bin/nc-config
#+end_src
puis trouver où il est installé à l'aide
#+begin_src bash
 >>> which nc-config
 OUT /usr/bin/nc-config
#+end_src
Finalement, il faut ajouter quelques lignes à notre fichier bash. Grossièrement, on ajoute le dossier /bin/ et le dossier /exe/ à notre /$PATH/, ainsi que les configurations pour utiliser NetCDF. Donc, on met
#+begin_src bash
 >>> export WWATCH3_NETCDF=NC4
 >>> export NETCDF_CONFIG=/usr/bin/nc-config
 >>> PATH=$PATH:/home/charlesedouard/Desktop/Travail/ww3/bin
 >>> PATH=$PATH:/home/charlesedouard/Desktop/Travail/ww3/exe
 >>> export PATH
#+end_src
Et tout devrait être dans la poche, même s'il y aura certainnement quelques ajustement à faire.

** Compilation du modèle 

Dans le dossier /bin/, on peut faire
#+begin_src bash
 >>> ./w3_setup /home/charlesedouardl/Desktop/Travail/wavewatch3 -c gfortran -s lizotte
#+end_src
pour s'assurer qu'on utilise les switches désirées. Ensuite, on peut faire le fameux
#+begin_src bash
 >>> ./w3_make
#+end_src
Finalement, il faut souvent repartir le terminal parce que le /.bashrc/ n'a pas été mis à jour.
Mentionnons aussi qu'il arrive souvent que le fichier de compilation ne fonctionne vraiment pas bien. Pour régler le problème, il faut s'assurer que la compilation fonctionne bien à l 'aide de /w3 make/, comme mentionné plus haut.\bigskip

Dans le cas qui nous intéresse, j'ai du revoir les options de compilation en ajoutant la ligne
#+begin_src bash
`$NETCDF_CONFIG --fflags`
#+end_src
dans le fichier de compilation /comp.gfortran/, comme on peut le voir à la ligne suivante.
#+begin_src bash
# netcdf include dir
if [ "$netcdf_compile" = 'yes']
then
    case $WWATCH3_NETCDF in
	NC3) opt="$opt -I$NETCDF_INCDIR" ;;
	NC4) if [ "$mpi_mod" = 'no' ]; then comp="`$NETCDF_CONFIG --fc`"; fi
	     opt="$opt -I`$NETCDF_CONFIG --includedir` `$NETCDF_CONFIG --fflags`" ;;
    esac
fi
#+end_src
Maintenant, ça marche très bien. Sommairement, mon compilateur /gfortran/ était incapable de trouver les modules /NetCDF/ étant donné que le fichier /netcdf.mod/ n'était pas dans mon répertoire courant, tout en étant bien installé. Par contre, la commande
#+begin_src bash
 >>> nc-config --fflags
#+end_src
nous amenait directement au bon dossier. C'est pourquoi elle a été ajouté. C'est un peu ridicule de perdre du temps là-dessus, considérant que sur une grappe de calcul ou un système universitaire, je n'aurais jamais eu ce problème.

** Switches du modèle

Alors maintenant, il faut les bonnes /switches/, mais c'est un peu ça le coeur de la question, on est là pour faire un ménage là-dedans. Donc, je ne m'étendrai pas dans les détails, seulement mentionner que nos input sont des fichiers de type /NetCDF/ et donc que ça nous prend la /switch/ NC4, d'où le problème de la section précédente. \bigskip

Nous utilisons les /switches/ 
#+begin_src bash
F90 SHRD LRB4 NOPA NOGRB PR3 FLX2 LN0 ST2 NL1 BT0 IC0 IS0 REF1 DB0 TR0 BS0 NC4
TRKNC UQ XX0 WNT1 WNX0 CRT1 CRX0 O0 O1 O2 02c 
#+end_src

** Paramètres du modèle (Surtout pour la grille)

On se souvient de la maîtrise de Eliot Bismuth, on doit donc garder en mémoire le tableau 4 qui contient toutes les infos (Voir tableau [[tab:bismuth]] suivant).
La plupart de ces infos vont servir à décrire la fonction /ww3 grid.inp/., genre avec le pas de temps, le nombre de fréquences, etc. 

#+name:tab:bismuth
#+attr_latex: :placement [!h]
#+caption: Tableau tiré de la maîtrise d'Éliot Bimuth.
|----------------------------------+--------------+--------+-------------------|
|----------------------------------+--------------+--------+-------------------|
| <l>                              |     <c>      |    <r> |        <c>        |
| Description de la variable       |   Symbole    | Valeur |      Unités       |
|----------------------------------+--------------+--------+-------------------|
| Taille de la grille              |    $L_x$     |      5 |        km         |
| Taille des points de grille      |  $\Delta x$  |    500 |         m         |
| Nombre de points de grille       |    $n_x$     |     10 |        --         |
| Épaisseur des floes              |     $h$      |    0.5 |         m         |
| Diamètre moyen des floes         | $\expval{D}$ |    200 |         m         |
| Période du maximum spectral      |    $T_p$     |      6 |         s         |
| Fréquence du maximum spectral    |    $f_p$     |    1/6 | $\mathrm{s}^{-1}$ |
| Hauteur significative des vagues |    $H_s$     |      1 |         m         |
| Minimum de fréquence du modèle   |  $f_{min}$   |   1/20 | $\mathrm{s}^{-1}$ |
| Maximum de fréquence du modèle   |  $f_{max}$   |  1/2.5 | $\mathrm{s}^{-1}$ |
| Nombre de fréquences du modèle   |     $n_f$    |     61 |        --         |
|----------------------------------+--------------+--------+-------------------|


Mentionnons aussi que d'autres quantités sont importantes lorsqu'on crée la configuration du modèle.
C'est pourquoi le tableau suivant est important.

#+attr_latex: :placement [!h]
#+caption: D'autres quantités qui seraient importante lors de la modélisation avec Wavewatch III.
|------------------------+------------+-------------+--------------------+----------------------------------------|
|------------------------+------------+-------------+--------------------+----------------------------------------|
| <l>                    |    <c>     |         <r> |        <c>         | <l>                                    |
| Description            |  Symbole   |      Valeur |       Unités       | Note                                   |
|------------------------+------------+-------------+--------------------+----------------------------------------|
| Champ gravitationnel   |    $g$     |        9.81 | $\mathrm{ms}^{-2}$ | --                                     |
| Vitesse de phase       |   $c_p$    | (max) 38.52 | $\mathrm{ms}^{-1}$ | $c_p = g/\omega$                       |
| Vitesse de groupe      |   $c_g$    | (max) 19.26 | $\mathrm{ms}^{-1}$ | $c_g = c_p/2$                          |
| Pas de temps           | $\Delta t$ |       25.00 |         s          | $\Delta t < \Delta x/c^{max}_g$        |
|------------------------+------------+-------------+--------------------+----------------------------------------|
| Nombre de fréquences   |    $nf$    |          40 |         --         | [cite:Voir @wwiii2016user switch NL2 ] |
| /Freq. Increment Factor/ |    $IF$    |        1.07 |         --         | [cite:Voir @wwiii2016user switch NL2 ] |
| Fréquence initiale     | $f_{min}$  |        0.05 | $\mathrm{s}^{-1}$  | Comme suggéré par Eliot Bismuth        |
| Fréquences maximale    | $f_{max}$  |          -- | $\mathrm{s}^{-1}$  | $f_{max} = f_{min}\cdot(IF)^{nf}$      |
| Nombre de directions   | $n_\theta$ |          36 |         --         | [cite:Voir @wwiii2016user switch NL2 ] |
|------------------------+------------+-------------+--------------------+----------------------------------------|

Mentionnons que dans Wavewatch III, il est impossible d'avoir un vecteur de fréquence dont les $\Delta f$ sont les même, comme chaque fréquence est le produit d'une ancienne fréquence avec le /Frequency increment factor/ (ce qui est un peu débile selon moi).
Il semble que j'ai clairement fait des erreurs avec ça dans le modèle avec Louis-Philippe.
Ça sera définitivement à vérifier.

** Grille

Dans la figure suivante, on retrouve toute l'information nécessaire pour recréer le fichier /ww3 grid.inp/.

#+attr_latex: :placement [!h]
#+name:fig:grid
#+caption: Grille initiale fournie à Wavewatch III.
\begin{figure}
\begin{center}
\begin{tikzpicture}
   \fill [red!10] (0,0) rectangle (10,3);
   \fill [blue!10] (1,1) rectangle (9,2);
   \draw[dotted] (0,0) grid (10,3);
   \draw[thick] (0,0) rectangle (10,3);
%%%
   \draw[|{latex}-{latex}|] (10.25,0) -- (10.25,3);
   \draw (10.25,1.5) node [rotate=90,below] {$150$ m};
   \draw[|{latex}-{latex}|] (0,-0.25) -- (10,-0.25);
   \draw (5,-0.5) node [below] {$500$ m};
%%%
   \filldraw [dotted] (-0.25,0.5) -- (0.5,0.5);
   \filldraw [dotted] (-0.25,2.5) -- (0.5,2.5) circle (1pt);
   \draw [decoration={brace}, decorate, thick] (-0.25,0.5) -- (-0.25,2.5);
   \draw (-0.5,1.5) node [rotate=90,above] { 25m à 125m};
%%%
   \filldraw [dotted] (0.5,3.25) -- (0.5,2.5);
   \filldraw [dotted] (9.5,3.25) -- (9.5,2.5) circle (1pt);
   \draw [decoration={brace}, decorate, thick] (0.5,3.25) -- (9.5,3.25);
   \draw (5,3.5) node [above] { 25m à 475m};
 %%%
   \filldraw (0.5,0.5) circle (1pt);
   \draw (0.5,0.5) node [right] {(25m,25m)};
\end{tikzpicture}
\end{center}
\end{figure}

** Vent

Même chose qu'en haut, mais en format NetCDF. Mentionnons qu'on met un vent homogène de 10 à 20 $\mathrm{ms}^{-1}$ sur tout le domaine pour l'instant. Par contre, il semble que le modèle ne le prenne pas en compte. C'est surement un problème de flux d'énergie. 

* Bibliographie
#+print_bibliography:
