#+title: Rapport hebdomadaire
#+subtitle: Contrat Été 2024
#+author: Charles-Édouard Lizotte
#+date:26/07/2024
#+LANGUAGE: fr
#+BIBLIOGRAPHY: master-bibliography.bib
#+OPTIONS: toc:nil title:nil 
#+LaTeX_class: org-report

\mytitlepage
\tableofcontents\newpage

* Maîtrise de Eliot Bismuth

** Équations en jeu
Rapidement, les équations d'évolution de l'énergie associée à chaque fréquences est donnée par
#+name:eq:energy
\begin{equation}
   \frac{1}{c_g}\dv{E}{t} = (1-f_i)\qty(S_{in} + S_{wc}) + f_i S_{ice}.
\end{equation}

S'il fallait isoler l'advection dans l'équation [[eq:energy]], nous aurions
#+name:eq:bismuth:advection
\begin{equation}
   \pdv{E(\omega,x,t)}{t} + \dot{x}\pdv{E}{x} + \dot{\omega} \pdv{E}{\omega} = 0
\end{equation}
Mais nous n'avons pas vraiment accès à toutes ces quantités.
Il faudra trouver un moyen d'observer le /spreading/ temporel des fréquences.\bigskip

\nb On va résoudre cette question dans les sections suivantes.

** Rappel rapide et conceptuelle d'une onde dans le contexte des vagues
La solution à l'équation d'onde est illustrée par une somme des solutions qui satisfont aussi la même équation (combination linéaire de solutions).
D'où la possibilité de représenter la vraie solution par une somme de Fourier.
La hauteur de la surface est ainsi illustrée par
#+name:eq:onde:basique
\begin{equation}
   h(\vb{x},t) = \sum_{i,j,k} A_{i,j,k}\cdot\sin(k_{x,i} \cdot x + k_{y,i}\cdot y - \omega_j t + \phi_k)\quad
    \text{où}\quad\left\lbrace\begin{matrix}
      k_{x,i} = k\cos(\theta_{i}), \\
      k_{y,i} = k\sin(\theta_{i}). \\
    \end{matrix}\right.
\end{equation}
Par contre, il existe une relation de dispersion (voir [[eq:relation:dispersion]] à la sous-section suivante), de sorte que [[eq:onde:basique]] devienne
\begin{equation}
   h(\vb{x},t) = \sum_{i,j} A_{i,j}\cdot\sin(\vb{k}(\theta_i)\cdot \vb{x} - \omega(\theta_i)\cdot t + \phi_j)
\end{equation}
On sait aussi qu'en moyenne, la phase est nulle, de sorte que $\expval{\phi_j} = 0$, donc on peut de nouveau se débarrasser d'un indice $j$.
Mentionnons aussi que la constante de phase n'est vraiment pas une quantitée importante dans la représentation mathématique de nos vagues, car les vagues se propagente et on s'intéresse plutôt au spectre, donc
\begin{equation}
   h(\vb{x},t) = \sum_{i} A_{i} \cdot\sin(\vb{k}_i \cdot \vb{x} - \omega_i \cdot t)
\end{equation}
Conceptuellement, dans une modèle à différences finies, la fréquence $\omega$ n'est qu'une variable comme une autre, de sorte que la hauteur de la surface pourrait aussi être illustrée par
#+name:eq:solution:vague
\begin{equation}
   \boxed{\quad h(\vb{x},t,k) = A(k) \cdot\sin(\vb{k} \cdot \vb{x} - \sqrt{gk}\cdot t).\quad}
\end{equation}
Ainsi, toutes les vagues se propageant à la surface de l'océan devraient avoir la composante [[eq:solution:vague]] précédente.
Pour obtenir les coefficients de notre transformée de Fourier spatiale, on intégrerait justement par rapport aux /vagues possibles mathématiquement/ (la forme qu'on a trouvé précédemment), soit
\begin{equation}
   A(k,t) = \iint_0^{x_{max}} \tilde{h}(\vb{x},t,k) \cdot \sin(\vb{k} \cdot \vb{x} - \sqrt{gk}\cdot t) \dd x\dd y.
\end{equation}
où $\tilde{h}$ fait justement référence au champ de vagues réel. 
Heureusement, grace au théorême de Parseval, on sait qu'il existe une invariant qui nous permet de dire
\begin{equation}
   E(t) \propto \sum_i \qty[A(k_i,t)]^2 = \sum_i \qty[h(\vb{x}_i,t)]^2
\end{equation}
d'oû la possibilité d'évaluer l'énergie pour chaque nombre d'onde $k_i$ et fréquences $\omega_i$.

** Lien avec la documentation de Wavewatch III 
Selon [cite/t/c:@william2013wave], dans le cas où le courant est nul, on peut toujours considérer la vitesse associée à l'advection comme la vitesse de groupe $c_g$.
Pour s'en convaincre, reprenons la documentation de Wavewatch III [cite:@wwiii2016user p.11 et 13].
On y retrouve une définition plus concrète du courant d'advection,
\begin{subequations}
\begin{align}
   & \dot{\vb{x}} = \vb{c}_g + \vb{U},\grande\\
   & \omega = \sigma + \vb{k}\cdot \vb{U},
\end{align}
\end{subequations}
où $\sigma$ est la fréquence relative ($2\pi f_r$), $\omega$ est la fréquence absolue ($2\pi f_a$) et $\vb{U}$ est la vitesse du courant d'advection. 
La relation de dispersion [cite:voir @wwiii2016user p.11] est illustrée par
#+name:eq:relation:dispersion
\begin{subequations}
\begin{align}
   &\sigma = \sqrt{ gk \tanh kd }, \\
   &\lim_{d\rightarrow\infty} \sigma = \sqrt{gk},
\end{align}
\end{subequations}
où la relation de dispersion pour les vagues océanique ($d\rightarrow\infty$) est illustrée en bas.
Les auteurs optent aussi pour une représentation de *la spectre de densité d'action des vagues* (/wave action density spectrum/) bien différente de [[eq:bismuth:advection]] (que j'ai adapté à 1 dimension), soit
\begin{equation}
   \pdv{N}{t} + \pdv{}{x}\qty(\dot{x} N) + \pdv{}{k} \qty(\dot{k}N)  = 0.
\end{equation}
ça revient absolument au même, voir le développement à l'aide d'une quantité fictive $\beta$.\bigskip

\exemple Soit une quantité $\beta(x,\omega,t)$.
Alors la dérivée en chaîne de $N$ par rapport à cette même quantité peut être exprimée par
\begin{align}
   \pdv{}{\beta}\qty(\dot{\beta} N) &= \pdv{}{\beta} \qty(\pdv{\beta}{t} N),\nonumber\\
   &= N \qty(\pdv{}{\beta} \qty(\pdv{\beta}{t})) + \pdv{\beta}{t}\pdv{N}{\beta},\nonumber\\
   &= N \qty(\pdv{}{t} \qty(\pdv{\beta}{\beta})) + \pdv{\beta}{t}\pdv{N}{\beta},\nonumber\\
   &= N \qty(\pdv{}{t} \qty(1)) + \pdv{\beta}{t}\pdv{N}{\beta},\nonumber\\
   &= \dot{\beta}\pdv{N}{\beta}.
\end{align}
Mentionnons aussi qu'on a plusieurs quantités ayant des noms similaires, soit le spectre d'énergie $E$ ou de variance (C'est la même chose), mais on utilise plutôt le *spectre de densité d'action des vagues* (/wave action density spectrum/) $N$ en raison de la conservation ($N = F/\sigma$),
\begin{equation}
  \boxed{\quad \grande\dv{N}{t} = \frac{S}{\sigma}.\quad }
\end{equation}

** Retour à la maîtrise d'Eliot Bismuth

On retrouve donc la formulation utilisée par [cite/t/c:@william2013wave] et dans la maîtrise de Bismuth.
Grossièrement, le modèle de Bismuth fait un pas d'advection à l'aide de la [[https://en.wikipedia.org/wiki/Lax%E2%80%93Wendroff_method][méthode de Lax-Wendroff,]] soit une méthode très efficace pour résoudre les équations différentielles hyperboliques de la forme
#+name:eq:lax
\begin{equation}
   \pdv{u(x,t)}{t} = \pdv{}{x}\qty(f(u(x,t))).
\end{equation}
Selon l'article de [cite/t/c:@william2013wave] (et comme précédemment), l'advection est définit par l'expression
\begin{equation}
   \dv{S}{t} = \pdv{S}{t} + c_g \pdv{S}{x} = 0,
\end{equation}
où $S$ est la fonction de densité spectrale, généralement exprimé par $N$ (comme partout précédemment) (À revérifier).
De toute manière, dans la maîtrise de Bismuth, nous prenons la convention pour $E(\omega,x,t)$, donc l'advection est exprimée par
#+name:eq:advec:bismuth
\begin{equation}
   \dv{E}{t} = \pdv{E}{t} + c_g \pdv{E}{x} = 0,
\end{equation}

\nb Il n'y a pas d'étalement selon les fréquences.
La raison est simple : l'étalement du aux fréquences est vu comme un terme source, car ça peut dépendre de plein de chose, dont principalement le /whitecapping/.
C'est pourquoi on ne tend pas vraiment à l'ajouter directement dans l'advection.\bigskip

Donc, en suivant [[eq:lax]], ont voit que le terme
\begin{equation}
   c_g \pdv{E}{x} = \pdv{}{x} \qty(c_g E) = \pdv{}{x} \qty(f(E(x,t))) \quad\quad \text{où} \quad\quad f\qty(E(x,t)) = c_g E.
\end{equation}
C'est *un cas linéaire* où $f(u) = A\cdot u$, soit
\begin{equation}
   u_i^{n+1} = u_i^n - \qty(\frac{\Delta t}{2\Delta x}) A \qty[u^n_{i+1} - u^n_{i-1}] + \qty(\frac{\Delta t^2}{2 \Delta x^2})A^2 \qty[u^n_{i+1} -2u^n_{i} + u^n_{i-1}],
\end{equation}
Avec nos quantités, nous aurions plutôt le schéma de Lax-Wendroff suivant : 
\begin{equation}
   \boxed{\quad E_i^{n+1} = E_i^n - \qty(\frac{\Delta t}{2\Delta x}) c_g \qty[E^n_{i+1} - E^n_{i-1}] + \qty(\frac{\Delta t^2}{2 \Delta x^2})c_g^2 \qty[E^n_{i+1} -2E^n_{i} + E^n_{i-1}].\quad}
\end{equation}

** Termes sources

*** Génération par le vent

Dans la maîtrise de Bismuth (2014), on assume une croissance linéaire, soit
\begin{equation}
   S = a + bE,
\end{equation}
où $a$ est la croissance initiale des vagues
Un peu comme dans le célèbre article de Phillips, on pourrait dire que c'est du bruit ou de la perturbation au niveau statistique.
La partie $bE$ est tirée d'un autre célèbre article, celui de Komen et al (1984), de sorte que
\begin{equation}
   b = 0.25\qty(\frac{\rho_A}{\rho_W})\omega\qty(28\frac{u_*}{c_p} - 1).
\end{equation}
Rapidement, $\omega$ est définit comme la fréquence radiale ($\omega \equiv 2\pi f\quad\qty[\rad\cdot\mathrm{s}^{-1}]$); $c_p$ est la vitesse de phase et $u_*$ est la /friction velocity/ (Vitesse de frottement).\bigskip

Bismuth (2014) utilise schéma suivant pour la vitesse de friction
\begin{equation}
   u_* = \left\lbrace \begin{matrix}
     &U_{10}\sqrt{1.2875\times10^{-3}} & \text{pour}\quad U_{10} < 7.5\ \mathrm{ms}^{-1}\\
     &U_{10}\sqrt{\qty(0.8+0.065U_{10})\times10^{-3}} & \text{pour}\quad U_{10}\geq 7.5\ \mathrm{ms}^{-1}\\
   \end{matrix}\right.
\end{equation}




Par contre, je suggère qu'on utilise plutôt le schéma dépendant du profil inverse logarithmique, comme exprimé dans ma maîtrise.
En premier lieu, on retrouve $u_*$ à l'aide de sa définition
\begin{equation}
   u_* = \sqrt{c_D} u_{10}.
\end{equation}


Pour trouver la valeur de $c_D$, on travaille avec la relation de Charnok [cite:@charnock1955wind] aussi tirée de [cite/t/c:@gill-atmosphere-ocean p.30], de sorte que 
#+name:cd
\begin{align}
   &&c_D = \qty[\frac{\kappa}{\ln(z/z_{\pt0})}]_{\pt z=10\pt m}^2
   && \text{où} &&
   z_0 = \frac{\alpha_{Ch}\tau_a}{\rho_a g} = \frac{\alpha_{Ch} c_D |u_{10}|^2}{g}. &&
\end{align}

|    <c>    | <l>          | <l>       | <l>                                                   |
| Variable  | Valeur       | Unités    | Description                                           |
|-----------+--------------+-----------+-------------------------------------------------------|
|    c_D    | À déterminer | --        | Coefficient de traînée                                |
|  \kappa   | 0.41         | --        | Constante de Von Karman                               |
|     z     | 10           | m         | Hauteur de la mesure du vent (Typiquement 10m)        |
|    z_0    | À déterminer | m         | Rugosité de l'interface (/roughness lenght/)            |
| \alpha_Ch | 0.0185       | --        | Valeur minimale du [[https://codes.ecmwf.int/grib/param-db/148][paramètre de Charnock]] (Voir ECWAM) |
|  \tau_a   | À déterminer | N m^{-2}  | Stress atmosphérique                                  |
|     g     | 9.81         | m s^{-2}  | Accélération gravitationnelle                         |
|  \rho_a   | 1.225        | Kg m^{-3} | Densité atmosphérique                                 |


*** /White-capping/ et étalement dans les fréquences

Le terme de /white-capping/ est exprimé [cite:@hasselmann1974spectral] comme
\begin{equation}
   S_{wc} = -\mu kE,
\end{equation}
où $\mu$ est un coefficient du rapport entre notre spectre et celui de Pierson-Moscowitz.
Ce dernier est exprimé par
\begin{equation}
   \mu - 2.36\times 10^{-5} \qty(\frac{\tilde{s}}{s_{PS}})^4 \frac{\tilde{\omega}}{\tilde{k}}.
\end{equation}
On utilise la lettre $s$ pour représenter la /steepness/ (ou la pente de nos vagues), de sorte que
+ $\tilde{s}$ est la pente moyenne définit par $\tilde{s} = \tilde{k} \sqrt{m_0}$ où $m_0$ est le $0^\text{ième}$ moment de notre spectre d'énergie -- autrement dit c'est l'énergie totale.
+ $s_{PM}$ est la même quantité mais pour le spectre de Pierson-Moscowitz ($\sim \sqrt{3.02\times10^{-3}}$).
On calcule $\tilde{\omega}$ et $\tilde{k}$ à l'aide des expressions
\begin{subequations}
\begin{align}
   \tilde{\omega} =& \qty[m_0^{-1} \int_0^\infty \omega^{-1} E(\omega)\pt \dd \omega\ \ ]^{-1} \\
   \tilde{k} =& \qty[m_0^{-1} \int_0^\infty k^{-1/2} E(\omega)\pt \dd \omega]^{-2}
\end{align}
\end{subequations}
Bismuth résoud les intrégrales précédentes à l'aide de la méthode des trapèzes (audacieux).

|       <c>        | <l>                      | <l>                         | <l>                                      |
|     Variable     | Valeur                   | Unités                      | Description                              |
|------------------+--------------------------+-----------------------------+------------------------------------------|
|       \mu        | À déterminer             | --                          | Rapport d'échelle avec Pierson-Moskowitz |
|   $\tilde{s}$    | À déterminer             | ?                           | Pente ou /steepness/                       |
|     $s_{PM}$     | $\sqrt{3.02\times10^-3}$ | ?                           | Pente pour Pierson-Moskowitz             |
| $\tilde{\omega}$ | À déterminer             | $\rad\cdot \mathrm{s}^{-1}$ | Fréquence moyenne                        |
|   $\tilde{k}$    | À déterminer             | $\rad\cdot \mathrm{m}^{-1}$ | Nombre d'onde moyen                      |
|      $m_0$       | À déterminer             | J                           | Énergie totale (premier moment)          |

*** Atténuation par la glace

L'atténuation par la glace prend une forme très simple, soit
\begin{equation}
   S_{ice} = -\alpha E
\end{equation}
où $\alpha$ est définit comme
\begin{equation}
   \alpha = \frac{\bar{\alpha}}{\expval{D}}.
\end{equation}
Officiellement les quantités précédentes sont
+ $\bar{\alpha}$, soit un coefficient d'atténuation empirique,
+ $\expval{D}$, la taille moyenne des floes.
Il faut résoudre un polynôme pour obtenir la quantité $\bar{\alpha}$, malheureusement.

|      <c>       | <l>          | <l>               | <l>                                   |
|    Variable    | Valeur       | Unités            | Description                           |
|----------------+--------------+-------------------+---------------------------------------|
|     \alpha     | À déterminer | $\mathrm{m}^{-1}$ | Coefficient d'atténuation             |
| $\bar{\alpha}$ | À déterminer | ?                 | Autre coefficient qui dépend de tout. |
|  $\expval{D}$  | À déterminer | m                 | Taille moyenne des floes              |



*** Limitation du changement de densité d'action

\begin{equation}
   \Delta S_{max} = \frac{8.1\times10^{-4}}{2\omega k^3 c_g}
\end{equation}


* Installation LaTeX avec Archlinux

Comme à l'habitude, une installation complète de [[https://wiki.archlinux.org/title/TeX_Live][TexLive]] est toujours nécessaire lors d'un changement de distribution.
À l'instar d'Ubuntu, l'action /sudo apt-get install texlive-full/ n'est pas disponible, car le concept de Archlinux est de tout compartimenter dans le but de minimiser les /packages/ actifs. 
Grossièrement, voici comment installer tous les compartiments nécessaire au fonctionnement de mon préambule LaTeX Org-Mode (en une seule commande) : 
#+begin_src bash
 >>> sudo pacman -S texlive-basic texlive-latex texlive-latexrecommended
                           texlive-fontsrecommended texlive-fontsextra texlive-bibtexextra
                           texlive-mathscience texlive-binextra texlive-latexextra
			   biber
#+end_src
+ Le /package/ « biblatex » est installée à l'aide de la *texlive-bibtexextra*. 
+ La commande /latexmk/ est installée à l'aide de [[https://bbs.archlinux.org/viewtopic.php?id=286621][texlive-binextra]].
+ Le /package/ « csquote » est installé à l'aide de [[https://bbs.archlinux.org/viewtopic.php?id=63529][texlive-latexextra]].
+ Pour faire marche LaTeX en Français, il faut installer [[https://archlinux.org/packages/extra/any/texlive-langfrench/][texlive-langfrench]].
+ Besoin de Biber pour gérer le lien entre les citations et la bibliographie (voir [[https://wiki.archlinux.org/title/TeX_Live][la page de Texlive]]). 


#+print_bibliography:
