#+title: Rapport hebdomadaire
#+subtitle: Contrat Été 2024
#+author: Charles-Édouard Lizotte
#+date:23/08/2024
#+LANGUAGE: fr
#+BIBLIOGRAPHY: master-bibliography.bib
#+OPTIONS: toc:nil title:nil 
#+LaTeX_class: org-report

\mytitlepage
\tableofcontents\newpage

* Retour sur le modèle de vagues

** Valeurs positives

Un gros problème tout au long du modèle était l'existence de valeurs négatives pour le spectre de vague -- ce qui ne fait aucun sens.
Pour pallier au problème, j'ai donc mis des filtres qui s'assurent d'avoir un minimum de 0 pour le spectre lorsque les termes source font descendre notre spectre trop bas.
+ Le premier est après l'advection;
+ Le second est juste après l'ajout des termes source. 

** Introduction de l'énergie dans les vagues

Le terme de croissance des vagues dans le modèle d'Eliot Bismuth est tiré des notes de Fabrice Ardhuin [cite:@Ardhuin2024ocean], qui sont elle aussi tirées d'un article de [cite/t/c:@snyder1981array].
Essentiellement, on assume que la croissance des vagues dans le terme source prend la forme
\begin{equation}
   S_{in}(f,\theta) = \sigma \beta E(f,\theta). 
\end{equation}
Dans l'équation précédente, le facteur $\beta$ est un taux de croissance adimensionnel.
Généralement, on utilise une fonction obtenue de manière empirique.
Par contre, [cite/t/c:@snyder1981array] ont réussi à la mettre en équation, soit
\begin{equation}
   \beta = \max \qty{0,\pt0.25\frac{\rho_a}{\rho_o} \qty[28\frac{u_\star}{C} \cos(\theta_\star - \theta) - 1]}.
\end{equation}
En 1 dimension, ça se traduirait par
\begin{equation}
   \boxed{\venti\quad\beta = \max \qty{0,\pt0.25\frac{\rho_a}{\rho_o} \qty[28\frac{u_\star}{C} - 1]},\quad}
\end{equation}
et c'est bien ce qu'on a! Par contre, je n'ai pas vu le /max/ dans le code de Bismuth...

** Pierson-Moskowitz

Y'a quelque chose de louche dans la maîtrise de Bismuth, c'est vraiment pas clair si les fréquences utilisées sont en $\mathrm{s}^{-1}$ ou en $\mathrm{Rad}\cdot\mathrm{s}^{-1}$.
Particulièrement où il y a la ligne de Pierson-Moscowitz.
C'est pourquoi je suis allé le chercher à la source, le /JONSWAP final report/ [cite:@hasselmann1973measurements].
Donc Pierson-Moskowitz, c'est
\begin{equation}
   E_{PM}(f) = \alpha g^2 (2\pi)^4 f^{-5} \exp[- \frac{5}{4} \qty(\frac{f}{f_m})^{-4}],
\end{equation}
mais si on prend le spectre JONSWAP, on multiplie par une composante qu'on appelle le /peak enhancement factor/ $\left(\pt\gamma^{g(f,\sigma)}\pt\right)$,
\begin{align}
   && E_{JONSWAP}(f) = E_{PM}(f)\times\gamma^{g(f,\sigma)}
   && \text{de sorte que} 
   && g(f,\sigma) = \exp[ \frac{-(f-f_m)^2}{2\sigma^2f_m^2}], &&
\end{align}
ce qui nous laisse 5 paramètres flottant, soient $f_m, \alpha, \gamma, \sigma_a, \sigma_b$.
Où l'on relit les derniers facteurs à l'aide de
\begin{equation}
   \sigma = \left\lbrace\begin{matrix}
       \sigma_a & \mathrm{si} & f \leq f_m,\\
       \sigma_b & \mathrm{si} & f > f_m.\\
   \end{matrix}
  \right.
\end{equation}

Par contre, Bismuth prend plutôt la formulation
\begin{equation}
   E_{JONSWAP}(\omega) = 0.2H_s^2 \qty(\frac{\omega_p^4}{\omega^5}) \exp{-\frac{5}{4}\qty(\frac{\omega_p}{\omega})^4} \times 3.3^{\exp{\frac{-(\omega-\omega_p)^2}{2\sigma^2 \omega_p^2}}}.
\end{equation}

Selon [cite/t/c:@hasselmann1973measurements], on devrait avoir les valeurs
\begin{align}
   &&\gamma = 3.3, && \sigma_a = 0.7, && \sigma_b = 0.9, &&
\end{align}
à l'équilibre -- c'est d'ailleur ce que Bismuth a mis.\bigskip

Donc, l'erreur vient du fait que dans son manuscrit, tout est en $\mathrm{Rad}\cdot\mathrm{s}^{-1}$ quand tout devrait être en $\mathrm{s}^{-1}$, ce qui se traduit par l'équation 2.15 de la maîtrise de Bismuth, soit
\begin{equation}
   E_{JONSWAP}(f) = 0.2\qty(\venti\frac{H_s^2}{2\pi}) \qty(\frac{f^4_p}{f^5}) \exp{-\frac{5}{4}\qty(\frac{f_p}{f})^4} \times 3.3^{\exp{\frac{-(\omega-\omega_p)^2}{2\sigma^2 \omega_p^2}}}.
\end{equation}
C'est une faute d'inattention. Dans les faits, il aurait du avoir
\begin{equation}
   \boxed{E_{JONSWAP}(f) = 0.2 \venti H_s^2 \qty(\frac{f^4_p}{f^5}) \exp{-\frac{5}{4}\qty(\frac{f_p}{f})^4} \times 3.3^{\exp{\frac{-(\omega-\omega_p)^2}{2\sigma^2 \omega_p^2}}}.}
\end{equation}
D'ailleurs, il ne cite pas que sa formulation vient de [cite/t/c:@goda1988variablity].
On en fait justement mention sur [[https://wikiwaves.org/Ocean-Wave_Spectra][l'article de Wikiwaves sur le JONSWAP]] en mentionnant qu'il faut faire attention à la conversion.

** Retour sur la méthode de Lax-Wendroff

Malheureusement, si l'on veut un /Superbee flux limiter/, on doit recoder la méthode de Lax-Wendroff.
En théorie, le limituer s'applique sur une quantité qu'on appelle le /flux/.
Cette quantité, c'est en fait ce qui sort d'un cube (ou d'un carré dans notre cas).\bigskip

On n'oublie pas qu'il faut résoudre
\begin{align}
   &&\pdv{E}{t} + c_g \pdv{E}{x} = 0 && \Longrightarrow &&   \pdv{E}{t} + \pdv{F(E)}{x}  = 0 \quad\text{où}\quad F(E) = c_gE &&
\end{align}

Grossièrement, on peut solutionner cette équation en additionnant un $\var{F}$, qui est en fait le /flux/ de notre fonction.
C'est justement ce que nous allons limiter dans 
\begin{equation}
   E_i^{n+1} = E_i^n - \qty(\frac{\var{t}}{\var{x}})\qty[\tall\ F_{i+\sfrac{1}{2}} - F_{i-\sfrac{1}{2}}\ ],
\end{equation}
Dans le cas de Lax-Wendroff, on peut représenter les flux sur chaque bords comme
\begin{subequations}
\begin{align}
   &F_{i-\sfrac{1}{2}} = \frac{1}{2}\qty(E_i^n - E_{i-1}^n) - \phi(E_{i-\sfrac{1}{2}}) \times\frac{1}{2}\fdv{t}{x}\qty(F(E_i^n) - F(E_{i-1}^n)),\\
   &F_{i+\sfrac{1}{2}} = \underbrace{\venti\frac{1}{2}\qty(E_{i+1}^n - E_i^n)}_{\mathrm{Moyenne}} - \ \phi(E_{i+\sfrac{1}{2}}) \times\underbrace{\venti\frac{1}{2}\fdv{t}{x}\qty(F(E_{i+1}^n) - F(E_i^n)).}_{\mathrm{Variation}}
\end{align}
\end{subequations}
où $\phi$ est le limiteur.
Dans le cas qui nous intéresse ([[https://en.wikipedia.org/wiki/Flux_limiter][limiteur /superbee/]])  -- car il existe toutes sortes de limiteurs -- nous avons

\begin{align}
   && && &&r_{i+\sfrac{1}{2}} = \qty(\frac{E_i - E_{i-1}}{E_{i+1} - E_i}),    && r_{i-\sfrac{1}{2}} = \qty(\frac{E_{i-1} - E_{i-2}}{E_{i} - E_{i-1}}) && &&
\end{align}
où le limiteur est exprimé par
\begin{equation}
   \phi = \mathrm{max} \qty{\begin{matrix}
       \pt\mathrm{min}(1, 2r)\\
       \mathrm{min}(2,\ r)\\
   \end{matrix}
   }.
\end{equation}

Voilà. Il faudra implémenter ça, plutôt que ma fonction d'algèbre linéaire, malheureusement.
C'est fait, en tout cas!

* Coefficient d'atténuation

Dany mentionnait l'article de [cite/t/c:@auclair2022model] qui offre un coefficient d'atténuation qui avait été proposé par [cite/t/c:@sutherland2019two].

** Article de [cite/t/c:@auclair2022model]


*** Atténuation des vagues par la glace
Grossièrement, on s'éloigne de la méthode de [cite/t/c:@Kohout2011wave], ce qui est une bonne nouvelle.
L'article de [cite/t/c:@sutherland2019two] semble empiriquement meilleur pour obtenir un coefficient d'atténuation physique $\alpha\ [\mathrm{m}^{-1}]$.
Dans l'article, on illustre le terme source de l'atténuation par la glace par
\begin{equation}
   S_{ice} = - \beta(A,h,f)\pt E_{waves}.
\end{equation}
Le coefficient d'atténuation temporel $\beta\ [\mathrm{s}^{-1}]$ est donné par 
\begin{equation}
   \beta = \frac{\nu \omega^2 \Delta_0}{2g\epsilon h},
\end{equation}
où
\begin{equation}
   \nu = \frac{1}{2} \epsilon^2 \omega h^2,
\end{equation}
est l'épaisseur relative d'une couche perméable de glace recouvrant notre eau et $\Delta_0$ est un paramètre relié à l'amplitude du mouvement des vagues à l'intérieur de cette même couche.
Il est donc suggéré de mettre ensemble ces deux équations pour obtenir,
\begin{equation}
   \beta = \frac{\epsilon \Delta_0 h \omega^3}{4g}.
\end{equation}
Les deux paramètres libres $\epsilon$ et $\Delta_0$ peuvent être combinés.
Selon les données de [cite/t/c:@sutherland2019two], on devrait avoir une relation empirique du genre
\begin{equation}
   \epsilon \Delta_0 = 0.5.
\end{equation}

Mentionnons qu'on peut aussi obtenir le taux d'atténuation par floe $a$ -- comme utilisé par [cite/t/c:@Kohout2011wave] -- et le mettre en relation avec le taux d'atténuation physique par distance $\alpha$. 
La relation est donnée par
\begin{equation}
   \alpha = \frac{A a}{D},
\end{equation}
où $D$ est le diamètre du floe et $A$ est la concentration de glace.


* Recherche d'une métrique sur l'hétérogénéité des paquets de glace

On pourrait commencer à regarder du côté de l'entropie.
CLairement, il faudrait voir si on peut relier une /mesure du désordre/ avec l'atténuation d'énergie dans un domaine de glace.

Mais comment représenter une mesure du désordre?











#+print_bibliography:
