#+title: Carnet de bord, Université McGill
#+author: Charles-Édouard Lizotte
#+date:20/10/2023
#+LATEX_CLASS: org-report
#+CITE_EXPORT: natbib
#+LANGUAGE: fr
#+BIBLIOGRAPHY: master-bibliography.bib
#+OPTIONS: toc:nil title:nil


\mytitlepage
\tableofcontents\newpage
* Debuggage et implémentation transfert de masse -- <2023-10-16 Mon>
DEADLINE: <2023-10-18 mer.>

** Vérifier que ce n'est pas un problème de viscosité -- <2023-10-16 Mon>
DEADLINE: <2023-10-17 Tue>
Avant tout, David a remarqué que les champs étaient très bruités, ce qui signifie qu'il y a clairement un manque à gagner en terme de viscosité.
N'oublions pas que nous sommes passées d'une viscosité au 4ème degré vers une viscosité au second degré quand nous cherchions le problème au bord, il y a quelques semaines. \bigskip

En sommes, de nouveaux test ont été effectuées pour le schéma de viscosité exprimé par
\begin{equation}
   \vb{D} = Ah_2 \cdot \laplacian{\uu} - Ah_4\cdot \gradient^4\uu.
\end{equation}
En ce mardi matin, les résultats sont exprimés dans le tableau [[tab:visco]].



#+NAME:tab:visco
#+CAPTION: Résumé des expériences réalisées dans le but de retrouver la bonne viscosité.
#+ATTR_LATEX: :align c|c|c|c|l
|--------+--------------------------------+--------+------------------------+------------------|
|   Ah_2 | Ah_4                           |     dx | min(\sfrac{$L_d$}{dx}) | Nombre d'itér.   |
| [ -- ] | [ -- ]                         | [ km ] |                 [ -- ] | [ -- ]           |
|--------+--------------------------------+--------+------------------------+------------------|
|--------+--------------------------------+--------+------------------------+------------------|
|    0.0 | (1\times10^{-5})\pt\times dx^4 |    3.9 |                  5.363 | 736 272 (Active) |
|    0.0 | (2\times10^{-5})\pt\times dx^4 |    3.9 |                  5.363 | 736 272 (Active) |
|    0.0 | (5\times10^{-5})\pt\times dx^4 |    3.9 |                  5.363 | 113              |
|    0.0 | (1\times10^{-4})\pt\times dx^4 |    3.9 |                  5.363 | 48               |
|    0.0 | (5\times10^{-4})\pt\times dx^4 |    3.9 |                  5.363 | 23               |
|--------+--------------------------------+--------+------------------------+------------------|
|--------+--------------------------------+--------+------------------------+------------------|


En somme, il semble que tous nos problèmes venaient bel et bien du changement de viscosité que nous avions appliqué pour régler le problème d'ondes de Kelvin aux bord (problème qui a été réglé [[file:rapport-2023-10-06.pdf][il y a deux rapports]]).\bigskip



** « Stencil » de transfert de masse
Louis-Philippe propose d'utiliser un stencil à 21 points pour redistribuer la masse.
En gros, on en retirerait sur le point fautif pour rejouter du /h/ aux points des alentours, ce qui en fait une redistribution horizontale de la masse.

#+NAME: fig:stencil
#+CAPTION: Stencil de redistribution de la masse.
\begin{figure}[!h]
\centering
\begin{tikzpicture}
   \fill [blue!5] (1,0) -- (4,0) -- (4,1) -- (5,1) -- (5,4) -- (4,4) -- (4,5) -- (1,5) -- (1,4) -- (0,4) -- (0,1) -- (1,1) -- (1,0);
   \fill [blue!12] (1,1) rectangle (4,4);
   \draw [dotted,thin] (1,0) grid (4,5);
   \draw [dotted,thin] (0,1) grid (5,4);
   \draw [] (1,0) -- (4,0) -- (4,1) -- (5,1) -- (5,4) -- (4,4) -- (4,5) -- (1,5) -- (1,4) -- (0,4) -- (0,1) -- (1,1) -- (1,0);
   \fill [cyan!50] (2,2) rectangle (3,3); 
   \draw [] (2,2) rectangle (3,3);
   %
   \draw (2.5,2.5) node {+1};
\end{tikzpicture}
\end{figure}

* Solution à la dérive de Stokes -- <2023-10-16 lun.>
Grossièrement, il est sorti deux possibilités pour régler le problème des petites échelles qui sortent de Wavewatch :
+ Il serait possible de diminuer la résolution de Wavewatch et de réinterpoler les points de courants à l'aide de la méthose employée dans la figure [[fig:interp]].

  #+NAME: fig:interp
  #+caption: « Stencil » utilisé pour obtenir le champs aux plus grandes échelles.
  \begin{figure}[h!]
  \begin{center}
  \begin{tikzpicture}
  % Big grid
  \fill [blue!5] (0,0) rectangle (3,3);
  \fill [blue!5] (3,3) rectangle (6,6);
  % Grid
  \draw (0,0) rectangle (6,6) ;
  \draw [dotted] (0,0) grid (6,6) ;
  \draw [step=3.0] (0,0) grid (6,6) ;
  % Carré
  \draw [cyan, thick] (2,2) rectangle (5,5) ;
  \fill [cyan!50, opacity=0.5] (3,3) rectangle (4,4);
  % Coordinates 
  \foreach \x in {1,2,3}
  \foreach \y in {1,2,3}
  {\draw (\x-0.5,\y-0.5) node [] {1,1};}
  %
  \foreach \x in {4,5,6}
  \foreach \y in {1,2,3}
  {\draw (\x-0.5,\y-0.5) node [] {2,1};}
  %
  \foreach \x in {1,2,3}
  \foreach \y in {4,5,6}
  {\draw (\x-0.5,\y-0.5) node [] {1,2};}
  %
  \foreach \x in {4,5,6}
  \foreach \y in {4,5,6}
  {\draw (\x-0.5,\y-0.5) node [] {2,2};}
  % Axis:
  \foreach \y in {1,2,3,4,5,6} {\draw (-0.5,\y-0.5) node [cyan] {\y};}
  \foreach \x in {1,2,3,4,5,6} {\draw (\x-0.5,-0.5) node [cyan] {\x};}
  %
  \end{tikzpicture}
  \end{center}
  \begin{equation}
     {\color{cyan}u(4,4)} = \qty(\sfrac{1}{9})\cdot u(1,1) + \qty(\sfrac{2}{9})\cdot u(2,1) + \qty(\sfrac{2}{9})\cdot u(1,2) + \qty(\sfrac{4}{9})\cdot u(2,2).
  \end{equation}
  \end{figure}




#+print_bibliography: 
