#+title: Carnet de bord, Université McGill
#+author: Charles-Édouard Lizotte
#+date: 03/06/2023
#+LATEX_CLASS: org-report
#+CITE_EXPORT: natbib
#+LANGUAGE: fr
#+BIBLIOGRAPHY: master-bibliography.bib
#+OPTIONS: toc:nil title:nil

\mytitlepage
\tableofcontents\newpage

* Erreurs rencontrées

** Ancienne méthode : Calculer la fonction de courant barotrope directement
Concrétement, l'ancienne méthode (voir [[file:rapport-2023-04-28.org][rapport précédent]]) consistait à trouver le rotationnel de $\uu_{BT}$, soit $\zeta_{BT} = \curl(\uu_{BT})$ pour solutionner l'équation de Poisson,
#+NAME: eq:poisson
\begin{equation}
   \laplacian(\psi_{BT}) =  \norm{\pt\curl{\uu_{BT}}\pt}.
\end{equation}
Une foit $\psi_{BT}$ en main, il est trivial (on s'en rapelle) de retrouver $\uu_{BT}$ à l'aide de la relation
\begin{equation}
   \uu = \kvf\times\gradient{\psi} = - \qty(\curl{\kvf\psi}).
\end{equation}

Malheureusement, certains problèmes émergeaient de l'application de cette méthode.

** Fluctuation relative de la fonction de courant barotrope
On définit la fluctuation relative de la fonction de courant barotrope $\delta \psi_{BT}$ de sorte que cette quantité satisfait la relation
\begin{equation}
   \psi_{BT}^{t+\delta t} = \psi_{BT}^t + \delta \psi_{BT} + Er\pt(\psi_{BT}),
\end{equation}
où $Er\pt(\psi_{BT})$ est une fonction pseudo-aléatoirement linéaire qui représente l'erreur numérique associée à une solution.
Cette dernière est proportionnelle à la solution de l'équation [[eq:poisson]], de sorte que
\begin{equation}
    Er\pt(\psi_{BT}) \propto \psi_{BT}.
\end{equation}
Alors, si l'on solve l'équation [[eq:poisson]] avec une précision de 5 chiffres par exemple, l'erreur par rapport à la fluctuation relative de la fonction de courant barotrope va se faire sentir sur les résultats.
Essentiellement, l'erreur numérique donne naissance à l'inégalité suivante
\begin{align}
   &&\text{Erreur relative} = \abs{\frac{Er\pt(\psi_{BT})}{\psi_{BT}}} \le \abs{ \frac{Er\pt(\psi_{BT})}{\delta \psi_{BT}} } &&\text{car (généralement)} && \abs{\psi_{BT}} \ge \abs{\delta \psi_{BT}}. &&
\end{align}
Donc, si l'on veut diminuer l'échelle de l'erreur numérique relative, on doit absolument solutionner $\delta \psi_{BT}$ plutôt que $\psi_{BT}$ sinon on perd une résolution importante.
Encore une fois, on y faisait référence dans le [[file:rapport-2023-04-28.org][rapport précédent]].
Si l'on faisait ça, nous aurions plutôt
\begin{align}
   \text{Erreur relative} = \underbrace{\qty{\ \abs{\frac{Er\pt(\delta\psi_{BT})}{\psi_{BT}}} \le \abs{ \frac{Er\pt(\delta\psi_{BT})}{\delta \psi_{BT}} }\ }}_\text{Solution $\delta \psi_{BT}$}
   <<
   \underbrace{\qty{\ \abs{\frac{Er\pt(\psi_{BT})}{\psi_{BT}}} \le \abs{ \frac{Er\pt(\psi_{BT})}{\delta \psi_{BT}} }\ }.}_\text{Solution $\psi_{BT}$}
\end{align}
Nous aurions donc bien des avantages à changer de méthode (on va le faire).

** Pas de temps

Techniquement, on peut argumenter que nous calculions 2 fois le pas de temps, accidentellement.
En différences finies, les équations du mouvement ont la forme
#+NAME: eq:evolution
\begin{equation}
   \uu^{t+\delta t} =
   \underbrace{\uu^t + RHS\cdot \Delta t\tall}_{\tilde{u}}
   \underbrace{- \gradient{\phi}\cdot \Delta t.\tall}_\text{Correction P}
\end{equation}
Par définition, on sait que
\begin{equation}
   \laplacian{\psi^{t+\delta t}} = \zeta^{t+\delta t},
\end{equation}
et on décompose en partie barotrope et barocline, de sorte que
\begin{align}
   && \laplacian{\psi^{t+\delta t}_{BT} + \psi^{t+\delta t}_{BC}} = \zeta^{t+\delta t}_{BT} + \zeta^{t+\delta t}_{BC}
   && \Longrightarrow
   && \laplacian{\psi^{t+\delta t}}_{BT} = \zeta^{t+\delta t}_{BT},
   && \text{et}
   && \laplacian{\psi^{t+\delta t}}_{BC} = \zeta^{t+\delta t}_{BC}.&&
\end{align}
Comme présenté à l'équation [[eq:evolution]], on peut décomposer le RHS de la dernière équation selon
\begin{align}
   \laplacian{\psi^{t+\delta t}}_{BT} = \tilde{\zeta}_{BT} - \cancelto{0}{\curl(\Delta t\cdot\gradient{\phi})}.
\end{align}
On solutionne l'équation de Poisson, on trouve $\psi^{t+\delta t}$, puis on retrouve le courant à l'aide de l'équation (à se souvenir), 
\begin{equation}
   \uu_{BT} = \kvf \times \qty(\gradient{\psi_{BT}}) = - \pt\curl(\psi_{BT}\kvf).
\end{equation}
Finalement, on additionne les parties barocliniques et barotropes pour obtenir
#+NAME: eq:uuu
\begin{equation}
   \uu^{t+\delta t} = \uu_{BT}^{t+\delta t} + \uu_{BC}^{t+\delta t}.
\end{equation}
Donc au final, s'il y a une erreur, elle est à l'équation [[eq:uuu]].
Concrétement, on additionne deux parties qui constituent une même chose.
Par contre, on obtient ces quantités depuis une quantités qui est entre deux pas de temps, à un temps peu définit.
Par exemple, on assume que
\begin{equation}
   \uu^{t+\delta t} = \tilde{\uu} - \gradient{\phi} \cdot \Delta t.
\end{equation}
Puis, on décompose en deux parties à l'aide de [[eq:uuu]], soit barotrope et baroclines,
\begin{subequations}
\begin{align}
   & \uu^{t+\delta t}_{BT} = \zmean{\tilde{\uu} - \gradient{\phi} \cdot \Delta t}  = \tilde{\uu}_{BT} - \gradient{\phi} \cdot \Delta t,\\
   & \uu^{t+\delta t}_{BC} = \uu^{t+\delta t} - \uu^{t+\delta t}_{BT}.
\end{align}
\end{subequations}
où $\zmean{\alpha}$ dénote la moyenne verticale d'une quantité $\alpha$.
On développe
\begin{align}
   \uu^{t+\delta t}_{BC}
   &= \uu^{t+\delta t} - \tilde{\uu}_{BT} + \gradient{\phi}\cdot \Delta t, \nonumber\\
   &= \tilde{\uu} - \gradient{\phi}\cdot \Delta t\ - \tilde{\uu}_{BT} + \gradient{\phi}\cdot \Delta t, \nonumber\\
   &= \tilde{\uu} - \tilde{\uu}_{BT}.
\end{align}
Cette dernière quantité est la définition de $\tilde{\uu}_{BC}$, donc on devrait être convaincu que
\begin{equation}
   \boxed{\hspace{0.4cm}\uu^{t+\delta t}_{BC}
   = \tilde{\uu} - \tilde{\uu}_{BT} = \tilde{\uu}_{BC}.\hspace{0.3cm}}
\end{equation}

* Nouvelle méthode proposée par David
Comme mentionné précédemment, il est possible de seulement calculer la correction à $\psi_{BT}$ plutôt que $\psi_{BT}$ pour minimiser l'erreur relative sur la solution.
On divise notre /RHS/ en deux parties, soit barotropes et baroclines,
\begin{equation}
   \vec{RHS} = \vec{RHS}_{BT} + \vec{RHS}_{BC}.
\end{equation}

Nous savons que les équations
#+NAME: eq:poisson
\begin{align}
   &&\laplacian{\psi^{t+\delta t}} = \curl{\uu^{t+\delta t}}
   &&\text{et}
   &&\laplacian{\psi^{t}} = \curl{\uu^{t}}&&
\end{align}
sont toujours valides. 
On se souvient aussi que les équations du mouvement en différence finie sont données par 
\begin{equation}
   \uu^{t+\delta t} =
   \uu^t + \vec{RHS}\cdot \Delta t
   - \gradient{\phi}\cdot \Delta t.
\end{equation}
Les parties barocline et barotrope sont respectivement exprimées par
\begin{subequations}
\begin{align}
   &\uu_{BT}^{t+\delta t} = \uu_{BT}^{t} + \vec{RHS}_{BT}\cdot \Delta t - \Delta t\cdot \gradient{\phi},\grande\\
   &\uu_{BC}^{t+\delta t} = \uu_{BC}^{t} + \vec{RHS}_{BC}\cdot \Delta t,
\end{align}
\end{subequations}
étant donné que le gradient de pression est un phénomène barotrope.
Pour cette même raison, on peut justement affirmer hors de tout doute que l'équation [[eq:poisson]] est séparable en partie barotrope et barcocline, soit
#+name: eq:btrelation
\begin{subequations}
\begin{align}
   &\grande\laplacian{\psi_{BT}^{t}}\ \pt = \curl{\uu_{BT}^{t}}
   \hspace{0.5cm}\text{et}\hspace{0.5cm}
   \laplacian{\psi_{BT}^{t+\delta t}} = \curl{\uu_{BT}^{t+\delta t}},\\
   &\grande\laplacian{\psi_{BC}^{t+\delta t}} = \laplacian{\tilde{\psi}_{BC}} = \curl{\uu_{BC}^{t+\delta t}} = \curl{\tilde{\uu}_{BC}},
\end{align}
\end{subequations}
car $\tilde{\uu}_{BC} = \uu^{t+\delta t}_{BC}$.
Donc, en développant la partie barotrope, on obtient
#+NAME: eq:tdeltatpoisson
\begin{equation}
   \laplacian(\psi_{BT}^t+\delta \psi \cdot \Delta t) = \curl(\uu^t_{BT} + \vec{RHS}_{BT}\cdot\Delta t - \cancelto{0}{\gradient{\phi}}\cdot \Delta t),
\end{equation}
puis en soustrayant la relation [[eq:btrelation]]a à la dernière équation ([[eq:tdeltatpoisson]]), on arrive à
\begin{equation}
   \laplacian(\delta \psi) = \curl(\vec{RHS}_{BT}).
\end{equation}
Finalement, on retrouve la partie barotrope de notre /RHS/ à l'aide de la relation
\begin{equation}
   \delta \uu_{BT} = \kvf\times\gradient(\delta \psi) = -\curl(\delta\psi\pt\kvf).
\end{equation}
Pour terminer avec
\begin{equation}
   \uu^{t+\delta t} =
   \uu^t + \Delta t\cdot\qty(\vec{RHS}_{BC}
   + \delta \uu_{BT}).
\end{equation}
